name: CI
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ "18", "19" ]
     
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node}}
